# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/DiffPALM',
                'doc_host': 'https://Bitbol-Lab.github.io',
                'git_url': 'https://github.com/Bitbol-Lab/DiffPALM',
                'lib_path': 'DiffPALM'},
  'syms': {'DiffPALM.core': {'DiffPALM.core.foo': ('core.html#foo', 'DiffPALM/core.py')}}}
