# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['msa_transformer', 'msa_alphabet', 'msa_batch_converter']

# %% ../nbs/00_core.ipynb 3
import torch
import esm

from .gumbel_sinkhorn_utils import *
from .msa_transformer_utils import read_msa, read_sequence

msa_transformer, msa_alphabet = esm.pretrained.esm_msa1b_t12_100M_UR50S()
msa_transformer = msa_transformer.eval()
msa_batch_converter = msa_alphabet.get_batch_converter()

